use_frameworks!

def shared_pods

  platform :ios, '10.0'

  pod 'Moya', '~> 12'
  pod 'RxCocoa'
  pod 'RxDataSources'
  pod 'RxReachability'
  pod 'RxSwift'
  
end

target 'CountryGuide' do
	shared_pods
end
